customLabels:
  node-role: "not-disruptable"

nodeSelector:
  node-role: "not-disruptable"

function:
  packages:
    - xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.8.0
    - xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.3.0
    - xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.2.1
